### ISSUE TITLE
Question about Sampling 

### ISSUE THREAD

**Issue by pprp** [kcyu2014/nas-landmarkreg#3]
I am appreciate your work, and this paper is clearly written.

But I have some question about contents in the Introduction. The sampling strategy can be divided into explicit ones such as RL, EA, Random and implicit ones which rely on a differentiable parameterization of the architecture space. 

In this part you enumerated several works:
- DARTS
- FBNet
- Improving one shot nas by suppressing the posterior fading
- Understanding and robustifying differentiable architecture search
- once for all

I am wondering that why Once for all belongs to implicit sampling methods.

**Comment by kcyu2014** [comment]
Once for all is built on top of ProxylessNAS, which supports both RL and implicit sampling (darts-like gradient update to architecture weights).

**Comment by pprp** [comment]
Thank you for your reply !
