### ISSUE TITLE
The way of loss.backward() in landmark regularization

### ISSUE THREAD

**Issue by pprp** [kcyu2014/nas-landmarkreg#5]
Thank you for releasing the source code! Landmark Regularization is simple and efficient. 

I wonder how to exec `loss.backward()` in the regularization term. 

![image](https://user-images.githubusercontent.com/29230784/167247503-ac68e813-cfbf-42a0-ace9-41ba7df06b66.png)

As we can see in the above formula, by forwarding the same batch `x`, subnet `ai` and subnet `aj` would get there losses.

However, it is likely that there is shared weight between subnet `ai` and subnet `aj`, which will cause the gradient conflict. 

How do you avoid gradient conficts?

**Comment by pprp** [comment]
The error is as below:

```
RuntimeError: Expected to mark a variable ready only once. This error is caused by one of the following reasons: 
1) Use of a module parameter outside the `forward` function. Please make sure model parameters are not shared across multiple concurrent forward-backward passes
2) Reused parameters in multiple reentrant backward passes. For example, if you use  multiple `checkpoint` functions to wrap the same part of your model, it would result in the same set of parameters been used by different reentrant backward passes multiple times, and hence marking a variable ready multiple times. DDP does not support such use cases yet.
```

What's more, in my settings, `find_unused_parameters=True` in DDP.

**Comment by kcyu2014** [comment]
Thanks for your interest. In my experiment setting, I do not call backward until the normal task loss and the ranking loss is computed. So there is no such gradient conflict.
